dlr-gtlab/intelligraph-module

src/CMakeLists.txt
src/intelli/data/object.cpp
src/intelli/data/object.h
src/intelli/future.cpp
src/intelli/graphexecmodel.cpp
src/intelli/graphexecmodel.h
src/intelli/gui/grapheditor.cpp
src/intelli/gui/grapheditor.h
src/intelli/gui/graphics/nodeobject.cpp
src/intelli/gui/graphics/nodeobject.h
src/intelli/gui/graphscene.cpp
src/intelli/gui/graphscene.h
src/intelli/gui/graphscenemanager.cpp
src/intelli/gui/graphscenemanager.h
src/intelli/gui/graphsceneselector.cpp
src/intelli/gui/graphsceneselector.h
src/intelli/gui/graphstatemanager.cpp
src/intelli/gui/graphstatemanager.h
src/intelli/gui/graphview.cpp
src/intelli/gui/graphview.h
src/intelli/gui/graphviewoverlay.cpp
src/intelli/gui/graphviewoverlay.h
src/intelli/gui/style.h
src/intelli/memory.h
src/intelli/module.cpp
src/intelli/node.h
src/intelli/private/graphexecmodel_impl.h
src/intelli/private/utils.h
tests/unittests/test_graphexecmodel.cpp
tests/unittests/test_helper.h

Closes #97
Double clicking a subgraph will now open it in the same viewer but in a nested level. The level can be traversed "upwards" using a graph/scene selection widget in the overlay. 
In addition...
- the Overlay-Widget was moved to a separate class. 
- The scenes and changing of the current scene is handles by a scene manager class
- The states were moved to their corresponding classes instead of everything being handled by the view class
- The exec model and auto evaluation state was move out of the view and scene class into the graph editor thus reducing coupling even more.
Initially we start at the root level:
Double clicking the subgraph and thus traversing the hierarchy "downwards" we will end up in the most nested graph. The graph/scene selector is updated accordingly and can …

Resolve: "Open Subgraphs in the same viewer but in a nested level"

---

src/intelli/gui/property_item/doubleinputwidget.cpp
src/intelli/gui/property_item/doubleinputwidget.h
src/intelli/gui/property_item/integerinputwidget.cpp
src/intelli/gui/property_item/integerinputwidget.h
src/intelli/node/propertyinput/doubleinputnode.cpp
src/intelli/node/propertyinput/intinputnode.cpp

Cleanup of some triggers for evaluation to avoid evaluation for not unchanged values

Resolve: "The number input nodes falsely trigger an evaluation if no value change has occured"

---

src/intelli/graphexecmodel.cpp
src/intelli/graphexecmodel.h
src/intelli/private/graphexecmodel_impl.h

Closes  #203.
The code evaluating the queued nodes had the potential to enter a infinite loop. This issue was fixed.

Resolve: "Graph execution sometimes stuck in infinite loop"

---

src/intelli/graph.cpp
src/intelli/graph.h
src/intelli/graphconnectionmodel.h
src/intelli/graphexecmodel.cpp
src/intelli/gui/graphscene.cpp
src/intelli/private/graph_impl.h
src/intelli/private/graphexecmodel_impl.h
tests/unittests/test_graphexecmodel.cpp

Closes #210
The reason for the crash was twofolds:
First issue:
1. if a subgraph was copied and pasted all of its subnodes were assigned new UUIDs. This must be done to avoid appending the same node with the same UUID twice.
2. When assigning the new UUIDs the temporary graph has not updated its global connection model (which uses UUIDs to refernce nodes instead)
3. The connection model was thus outdated/invalid which lead to hard to trace errors/inconsistencies as it contained nodes and connections that did not exist
Second issue:
1. the graph node was appended to the root graph
5. when a graph node is appended the exec model first registers all nodes of the subgraph (here input/output provider)
6. once a node is appended the exec model attempts to execute the node
7. at this point the …

Resolve: "Crash while grouping nodes with auto evaluation enabled"

---

CHANGELOG.md
src/CMakeLists.txt
src/intelli/node.cpp

hid size and position properties of nodes, renamed intelligraph specific compiler flags

Hide size and position properties of nodes in dev mode

---

CHANGELOG.md
src/intelli/graphexecmodel.cpp
src/intelli/memory.h
src/intelli/private/graphexecmodel_impl.h

fixed issue with propagation of node evaluation failure if `setNodeData` was called after `evalFailed`

Fixed propagation of node evaluation failure if node is executed in another thread

---

src/intelli/gui/grapheditor.cpp
src/intelli/gui/graphscene.cpp
src/intelli/gui/graphscenemanager.cpp
src/intelli/gui/graphscenemanager.h
src/intelli/gui/graphview.cpp
src/intelli/gui/graphview.h
src/intelli/gui/graphviewoverlay.cpp

I added a connection to close the editor. The signal is triggered if the graph is deleted or (as it also deletes the graph) the project is closed.

Close graph editor if graph is deleted or project is closed

---

src/intelli/graphconnectionmodel.h

Fixed non constant template parameter in connection model. For what ever reason my clang-cmake config (or whatever) did not like accessing a static constexpr of a variable, but demanded to use the class type directly. Maybe its clang specific feature.
clang 18.1.8
cmake 3.31.1
Qt 5.15.16

[Clang] Fix build error due to non constant Template Parameter

---

src/intelli/exec/detachedexecutor.cpp
src/intelli/graph.cpp
src/intelli/graph.h
src/intelli/graphconnectionmodel.h
src/intelli/graphexecmodel.cpp
src/intelli/gui/graphscene.cpp
src/intelli/private/graph_impl.h
src/intelli/private/graphexecmodel_impl.h
src/intelli/private/utils.h
tests/unittests/test_graph.cpp

Closes #244 
- fixed the bugged behavior by resetting both connection models. This was by far the simplest approach and seemed to work all times.
Addtionally:
- performed light refactoring
- updated logging statements to clearly state component that message belongs to

Resolve: "Moving graph nodes from one graph to another leaves connection models in incorrect state"

---

CHANGELOG.md
src/intelli/dynamicnode.cpp
src/intelli/dynamicnode.h
src/intelli/graph.cpp
src/intelli/graph.h
src/intelli/graphbuilder.cpp
src/intelli/graphbuilder.h
src/intelli/graphdatamodel.h
src/intelli/graphexecmodel.cpp
src/intelli/graphexecmodel.h
src/intelli/gui/graphics/nodeobject.cpp
src/intelli/gui/graphics/nodeobject.h
src/intelli/gui/nodegeometry.cpp
src/intelli/gui/nodegeometry.h
src/intelli/gui/nodepainter.cpp
src/intelli/gui/nodepainter.h
src/intelli/gui/nodeui.cpp
src/intelli/gui/nodeui.h
src/intelli/gui/style.cpp
src/intelli/gui/style.h
src/intelli/module.cpp
src/intelli/nodedatafactory.cpp
src/intelli/nodedatafactory.h
src/intelli/nodefactory.cpp
src/intelli/nodefactory.h
src/intelli/private/graph_impl.h
src/intelli/private/graphexecmodel_impl.h

Interfaces that were pimpled:
Added padding other measures to reduce chance of ABI changes:
Closes #232

Resolve: "Use Pimpl to reduce future API/ABI-incompatibilities"

---

src/intelli/graph.cpp

reordered deletion of nodes and connections when deleting a graph to avoid inconsistencies in global connection model

Fix inconsistencies when deleting connections to input providers

---

src/intelli/gui/widgets/doubleinputwidget.cpp
src/intelli/gui/widgets/editablelabel.cpp
src/intelli/gui/widgets/intinputwidget.cpp

As the line edit does not take ownership of its validator, we need to add a parent object to the newly created validators.
Found with AddressSanitizer.

Fixed multiple memory leaks

---

src/intelli/node/genericcalculatorexec.cpp

- fix calculator executor node not updating correctly when disconnecting ports
- collapse default category
- hide 'skip' entry in default category
Closes #262

Resolve: "Calculator Executor Node does update correctly when disconnecting ports"

---

CHANGELOG.md
src/intelli/gui/graphics/nodeobject.cpp
src/intelli/gui/graphics/nodeobject.h
src/intelli/gui/graphscene.cpp
src/intelli/gui/graphscene.h
src/intelli/gui/graphview.cpp
src/intelli/node.cpp
src/intelli/node.h

Closes #41 - moving a node now creates an undo command

Resolve: "Changing a Node Position should create an undo command"

---

src/CMakeLists.txt
src/intelli/core.cpp
src/intelli/node/objectsink.cpp
src/intelli/node/objectsink.h

This PR is relevant for HGF presentation. With the new implemented node it is possible to write an object from the graph to the project datamodel instance. If the object from the graph and the target are of the same class the object is overwritten, else it is appended.

Object Sink Node implementation

---

CHANGELOG.md
src/intelli/graph.h
src/intelli/gui/graphscene.cpp
src/intelli/node.h
src/intelli/private/graph_impl.h

Closes #277 - fixed the instantiation of shared outgoing connections when grouping nodes which caused certain outgoing connections to disappear when grouping nodes.

Resolve: "Grouping nodes into subgraphs causes some connections to disappear"

---

CHANGELOG.md
src/intelli/graphexecmodel.cpp
tests/unittests/test_graphexecmodel.cpp

Closes #278 - `Node::evaluated` is no longer triggered twice

Resolve: "Node::evaluated is triggered twice"

---

CHANGELOG.md
src/CMakeLists.txt
src/intelli/dynamicnode.cpp
src/intelli/dynamicnode.h
src/intelli/graph.cpp
src/intelli/graphconnectionmodel.h
src/intelli/gui/graphics/nodeobject.cpp
src/intelli/gui/graphics/nodeobject.h
src/intelli/gui/graphscene.cpp
src/intelli/gui/graphscene.h
src/intelli/gui/graphstatemanager.cpp
src/intelli/gui/graphstatemanager.h
src/intelli/gui/guidata.cpp
src/intelli/gui/guidata.h
src/intelli/gui/nodegeometry.cpp
src/intelli/gui/nodegeometry.h
src/intelli/gui/nodepainter.cpp
src/intelli/gui/nodepainter.h
src/intelli/gui/ui/guidataui.cpp
src/intelli/gui/ui/guidataui.h
src/intelli/gui/ui/logicnodeui.cpp
src/intelli/gui/ui/logicnodeui.h
src/intelli/module.cpp
src/intelli/package.cpp
tests/unittests/test_graph.cpp

Closes #282 - allowed nodes to be collapsed using the context menu
The collapsed state is stored in a data object per graph. The states are not merged when expanding a graph or grouping nodes.

Resolve: "Collapse nodes visually"

---

src/intelli/gui/graphscene.cpp

Closes #298 - fixed grouping dummy nodes
Fixed that comments can be grouped as well without a node being selected

Fixed disabling grouping dummy nodes

---

CHANGELOG.md
src/intelli/exec/detachedexecutor.cpp
src/intelli/exec/dummynodedatamodel.h
src/intelli/graphbuilder.cpp
src/intelli/graphexecmodel.cpp
src/intelli/graphexecmodel.h
src/intelli/gui/grapheditor.cpp
src/intelli/node/genericcalculatorexec.cpp
src/intelli/node/input/objectinput.cpp
src/intelli/node/objectsink.cpp
src/intelli/nodedatainterface.h
src/intelli/private/graphexecmodel_impl.h

Closes #32 - introduced a scope object for evaluating intelli graphs
Closes #256 - use scope object for accessing linked objects
Scope is accessible using `exec::nodeDataInterface(*this)->svope()`. Note: `exec::nodeDataInterface` may yield null.

Introduced a Scope Object for Evaluating Intelli Graphs
